name: python-ci
run-name: ${{ github.actor }} is running {{ github.event_name }} on ${{ github.ref }}
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
env:
    PYTHON_VERSION: "3.10"

jobs:
    build1:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
#            - name: Test with pytest
#              run: |
#                  pytest
