name: python-CI
run-name: ${{ github.actor }} is running ${{ github.event_name }} on ${{ github.ref }}
on:
    push:
        branches: [ "main", "develop" ]
    pull_request:
        branches: [ "main" ]
env:
    PYTHON_VERSION: "3.10"
    TIMESTAMP: $(date +%Y%m%d-%H%M%S)
jobs:
    python-ci:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./src
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: Install dependencies
              run: |
                  mkdir -p ../reports/flake ../reports/htmlcov
                  python -m pip install --upgrade pip
                  pip install flake8 pytest pytest-cov
                  pip install coverage
                  pip install -r requirements.txt

            - name: Lint with flake8
              run:  flake8 . --show-source --statistics --output-file=..reports/flake/results_Lint.txt

            - name: Check Compatibility
              run: flake8 . --max-complexity=10 --statistics --exit-zero --output-file=..reports/flake/results_Compatibility.txt

            - name: Test with including coverage
              run: coverage run -m unittest discover .

            - name: Coverage REPORT
              run: coverage html --directory=..reports/htmlcov

            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                name: test-coverage-report-${{ env.TIMESTAMP }}
                path: ./reports/htmlcov/

            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                name: flake8-report-${{ env.TIMESTAMP }}
                path: ./reports/flake/